"""measurements_and_debug_info

Revision ID: 2fb99c391350
Revises: fc6f5ab4bb5c
Create Date: 2024-05-03 15:27:32.206847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb99c391350'
down_revision: Union[str, None] = 'fc6f5ab4bb5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('inside_temperature', sa.Float(), nullable=False),
    sa.Column('outside_temperature', sa.Float(), nullable=False),
    sa.Column('inside_humidity', sa.Float(), nullable=False),
    sa.Column('outside_humidity', sa.Float(), nullable=False),
    sa.Column('humidifier_relay_state', sa.Boolean(), nullable=False),
    sa.Column('pump_relay_state', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('debug_info',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('pump_hysteresis_delta', sa.Integer(), nullable=False),
    sa.Column('top_humidity_boundary', sa.Integer(), nullable=False),
    sa.Column('bottom_humidity_boundary', sa.Integer(), nullable=False),
    sa.Column('automatic_humidity_control', sa.Boolean(), nullable=False),
    sa.Column('pid_kp', sa.Float(), nullable=False),
    sa.Column('pid_ki', sa.Float(), nullable=False),
    sa.Column('pid_kd', sa.Float(), nullable=False),
    sa.Column('pump_automatic_control', sa.Boolean(), nullable=False),
    sa.Column('pump_temperature_delta', sa.Float(), nullable=False),
    sa.Column('target_temperature', sa.Float(), nullable=False),
    sa.Column('temperature_sensor_offset', sa.Float(), nullable=False),
    sa.Column('first_after_reboot', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['timestamp'], ['measurements.timestamp'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debug_info')
    op.drop_table('measurements')
    # ### end Alembic commands ###
