import type { Metadata } from "next";
import "../globals.css";
import SideBar from "../_components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SideBar>
          {children}
        </SideBar>
      </body>
    </html>
  );
}
